name: Create and publish a Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create version string
        id: version
        run: |
          DATE=$(date +'%Y-%m-%d')
          COMMIT_SHA=${GITHUB_SHA:0:7}
          echo "VERSION=${DATE}-${COMMIT_SHA}" >> $GITHUB_ENV
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}"  --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - Zname: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/infra-registry-creds:${{ env.VERSION }}